### ISSUE TITLE
Some files are missing, could they be added automatically?

### ISSUE THREAD

**Issue by LeonardoFBR** [EKQRCalamity/SWRevamped#1]
![image](https://user-images.githubusercontent.com/72281630/233200486-5490cc74-85ec-47f1-8f3f-07f555324e9c.png)

**Comment by LeonardoFBR** [comment]
![image](https://user-images.githubusercontent.com/72281630/233233875-614b9a55-7acf-4bda-acef-7e418f72f432.png)

**Comment by LeonardoFBR** [comment]
Would you be so kind to share the dlls? The ones I got don't have functions that you use

**Comment by EKQRCalamity** [comment]
Are you using the dlls from the Oasys SDK?

**Comment by EKQRCalamity** [comment]
You can find them on the Oasys discord if you are interested. This isnt a full script and only a module if you came for a full script here :)

**Comment by EKQRCalamity** [comment]
For a full script I would take a look at an LView Version for 64 bit or maybe cracked Toir (will probably need 64 update revisions tho dont know what the last cracked version is) and how to find offsets to update it yourself.

**Comment by EKQRCalamity** [comment]
Added the dlls anyway now. Can be found in Oasys SDK
