### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by VarNotUsed** [EKQRCalamity/SWRevamped#3]
Hi, würde gerne eine Seite für lol Scripts oder LVL Bots aufbauen, eventuell auch mehr. Hätte dich gerne an Board. Schreib mir gern auf DC, wenn du Interesse hast. 

Discord: varnotused

**Comment by EKQRCalamity** [comment]
Ich bin schon Teil eines Teams. Jedoch danke der Nachfrage.
